doctrine:
    dbal:
        dbname: '%database.name%'
        host: '%database.hostname%'
        port: 3306
        user: '%database.username%'
        password: '%database.password%'
        driver: 'pdo_mysql'
        url: '%database.url%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            ApiBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/ApiBundle/Entity'
                prefix: 'App\ApiBundle\Entity'
                alias: ApiBundle
            MaintenanceBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/MaintenanceBundle/Entity'
                prefix: 'App\MaintenanceBundle\Entity'
                alias: MaintenanceBundle
            BookingBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/BookingBundle/Entity'
                prefix: 'App\BookingBundle\Entity'
                alias: BookingBundle
            CoreBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CoreBundle/Entity'
                prefix: 'App\CoreBundle\Entity'
                alias: BookingBundle