# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    database.name: '%env(resolve:DATABASE_NAME)%'
    database.hostname: '%env(resolve:DATABASE_HOSTNAME)%'
    database.username: '%env(resolve:DATABASE_USERNAME)%'
    database.password: '%env(resolve:DATABASE_PASSWORD)%'
    database.url: '%env(resolve:DATABASE_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/*/{DependencyInjection,Entity,Tests}/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\ApiBundle\Controller\:
        resource: '../src/ApiBundle/Controller/'
        tags: ['controller.service_arguments']

    App\BookingBundle\Controller\:
        resource: '../src/BookingBundle/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\MaintenanceBundle\Controller\:
        resource: '../src/MaintenanceBundle/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\CoreBundle\Controller\:
        resource: '../src/CoreBundle/Controller/'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
